/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */

package cobacrud;

import java.sql.Connection;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author WIRA
 */
public class MenuKaryawan extends javax.swing.JInternalFrame {

    /** Creates new form MenuKaryawan */
    public MenuKaryawan(){
        
        initComponents();
        tampil_tabel();
    }

    /** This method is called from within the constructor to
     * initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is
     * always regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        TabKar = new javax.swing.JTable();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        nama = new javax.swing.JTextField();
        alamat = new javax.swing.JComboBox<>();
        AddButt = new javax.swing.JButton();
        clear = new javax.swing.JButton();
        jButton1 = new javax.swing.JButton();
        jLabel4 = new javax.swing.JLabel();
        idField = new javax.swing.JTextField();
        DelButt = new javax.swing.JButton();

        jLabel1.setText("jLabel1");

        setTitle("Menu Karyawan");

        TabKar.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "No", "ID", "Nama", "Alamat"
            }
        ));
        TabKar.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                TabKarMouseClicked(evt);
            }
        });
        jScrollPane1.setViewportView(TabKar);

        jLabel2.setText("Nama");

        jLabel3.setText("Alamat");

        alamat.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Pilih Kota", "Aceh", "Bandung", "Banjarmasin", "Bogor", "Makassar", " " }));

        AddButt.setText("Tambah");
        AddButt.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                AddButtActionPerformed(evt);
            }
        });

        clear.setBackground(new java.awt.Color(255, 255, 255));
        clear.setText("Bersihkan");
        clear.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                clearActionPerformed(evt);
            }
        });

        jButton1.setText("Ubah");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });

        jLabel4.setText("ID");

        idField.setEditable(false);

        DelButt.setText("Hapus");
        DelButt.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                DelButtActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(AddButt)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jButton1)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(DelButt))
                    .addComponent(clear)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel3)
                            .addComponent(jLabel2)
                            .addComponent(jLabel4))
                        .addGap(18, 18, 18)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(nama, javax.swing.GroupLayout.DEFAULT_SIZE, 174, Short.MAX_VALUE)
                            .addComponent(alamat, 0, 174, Short.MAX_VALUE)
                            .addComponent(idField))))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 41, Short.MAX_VALUE)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 301, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(15, 15, 15)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel4)
                            .addComponent(idField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel2)
                            .addComponent(nama, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(jLabel3)
                            .addComponent(alamat, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(31, 31, 31)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(AddButt)
                            .addComponent(jButton1)
                            .addComponent(DelButt))
                        .addGap(18, 18, 18)
                        .addComponent(clear))
                    .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 271, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(27, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void AddButtActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_AddButtActionPerformed
        // TODO add your handling code here:
        String Nm = nama.getText(); //Get Text Field
        String kota = (String) alamat.getSelectedItem(); // Get Combo Box
        if (Nm.equals("")){
            JOptionPane.showMessageDialog(null, "Isi nama terlebih dahulu");
        } else if (kota.equals("Pilih Kota")){
            JOptionPane.showMessageDialog(null, "Isi alamat terlebih dahulu");
        } else{
        
        try {
            String AddSQL = "INSERT INTO `karyawan` (nama, alamat) VALUES ('"+Nm+"', '"+kota+"' )";
            java.sql.Connection Vcon = (Connection)ConnectDB.configDB();
            java.sql.PreparedStatement s = Vcon.prepareStatement(AddSQL);
            s.execute();
            JOptionPane.showMessageDialog(null, "Tambah Data Berhasil");
        } catch (Exception e) {
            JOptionPane.showMessageDialog(null, "Tambah Data Gagal");
            JOptionPane.showMessageDialog(this, e.getMessage());
        }
        tampil_tabel();
        clear();
        }
        
    }//GEN-LAST:event_AddButtActionPerformed

    private void clearActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_clearActionPerformed
        // TODO add your handling code here:
        clear();
    }//GEN-LAST:event_clearActionPerformed

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        // TODO add your handling code here:
        String id = idField.getText();
        String nm = nama.getText();
        String almt = (String) alamat.getSelectedItem();
        
        if (nm.equals("")){
            JOptionPane.showMessageDialog(null, "Isi nama terlebih dahulu");
        } else if (almt.equals("Pilih Kota")){
            JOptionPane.showMessageDialog(null, "Isi alamat terlebih dahulu");
        } else{
        try {
            String Usql = "UPDATE karyawan SET id = '"+id+"', nama = '"+nm+"', alamat ='"+almt+"' WHERE id = '"+id+"'";
            java.sql.Connection Vcon = (Connection)ConnectDB.configDB();
            java.sql.PreparedStatement pst = Vcon.prepareStatement(Usql);
            pst.execute();
            JOptionPane.showMessageDialog(null, "Update Data Berhasil");
            tampil_tabel();
            clear();
            
        } catch (Exception e) {
            JOptionPane.showMessageDialog(null, "Update Data Gagal");
            JOptionPane.showMessageDialog(this, e.getMessage());
        }
        }
    }//GEN-LAST:event_jButton1ActionPerformed

    private void TabKarMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_TabKarMouseClicked
        // TODO add your handling code here:
        
        int row = TabKar.rowAtPoint(evt.getPoint());
        //int colmn = TabKar.columnAtPoint(evt.getPoint());
        String id = TabKar.getValueAt(row, 1).toString();
        idField.setText(id);
        
        String nm = TabKar.getValueAt(row, 2).toString();
        nama.setText(nm);
        
        String almt = TabKar.getValueAt(row, 3).toString();
        alamat.setSelectedItem(almt);
    }//GEN-LAST:event_TabKarMouseClicked

    private void DelButtActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_DelButtActionPerformed
        // TODO add your handling code here:
        String id = idField.getText();
        String name = nama.getText();
        String alamt = (String) alamat.getSelectedItem();
        
        if (name.equals("")){
            JOptionPane.showMessageDialog(null, "Pilih data terlebih dahulu");
        } else if (alamt.equals("Pilih Kota")){
            JOptionPane.showMessageDialog(null, "Pilih data alamat terlebih dahulu");
        } else{
        try {
            //Query
            String query = "DELETE FROM karyawan WHERE id ='"+id+"'";
            //Koneksi
            java.sql.Connection Vcon = (Connection)ConnectDB.configDB();
            //Statement
            java.sql.PreparedStatement stm = Vcon.prepareStatement(query);
            //Eksekusi Query
             stm.execute();
            //Tampil Notif Berhasil
            JOptionPane.showMessageDialog(null, "Berhasil Hapus Data");
             tampil_tabel();
             clear();
        } catch (Exception e) {
            JOptionPane.showMessageDialog(null, "Gagal Hapus Data");
            JOptionPane.showMessageDialog(this, e.getMessage());
        }
        }
    }//GEN-LAST:event_DelButtActionPerformed

    private void tampil_tabel(){
        DefaultTableModel tb = new DefaultTableModel();
        tb.addColumn("No");
        tb.addColumn("ID");
        tb.addColumn("Nama");
        tb.addColumn("Alamat");
        
        try {
            int counter = 1;
            
    // Query
            String queSQL = "SELECT * FROM Karyawan";
    // Fungsi Koneksi
            java.sql.Connection Vcon = (Connection)ConnectDB.configDB();
    
    // Kirim Parameter Fungsi Java ke SQL
            java.sql.Statement s = Vcon.createStatement();
    
    // Eksekusi Query
            java.sql.ResultSet r = s.executeQuery(queSQL);
    // Looping
            while (r.next()){
                tb.addRow(new Object[]{
                counter++, r.getString(1),r.getString(2),r.getString(3)
            });
            }
            TabKar.setModel(tb);
        } catch (Exception e) {
        }
    }
    
    private void clear(){
        idField.setText("");
        nama.setText(""); //Get Text Field
        alamat.setSelectedIndex(0);
    } 

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton AddButt;
    private javax.swing.JButton DelButt;
    private javax.swing.JTable TabKar;
    private javax.swing.JComboBox<String> alamat;
    private javax.swing.JButton clear;
    private javax.swing.JTextField idField;
    private javax.swing.JButton jButton1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTextField nama;
    // End of variables declaration//GEN-END:variables

}
